#spring.application.name=TicketManagement
#spring.data.mongodb.uri=mongodb://localhost:27017/user
#server.port:8080
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=acterakash@gmail.com
#spring.mail.password=sxgnhjgyqgmixyhp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/TicketManagement

  mail:
    host: smtp.gmail.com
    port: 587
    username: acterakash@gmail.com
    password: sxgnhjgyqgmixyhp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 20MB